name: ${project.name}
version: ${project.version}
main: ${project.group}.${project.name.toLowerCase()}.${project.name}
api-version: 1.19
author: Blugon
libraries:
  - io.github.monun:kommand-core:3.0.0